### ISSUE TITLE
Use the official logo

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/Viewers#4]
@pieper we need to use the NCI IDC logo for the production deployment. Can you update to use the one here: https://drive.google.com/drive/folders/1KnH0sfGX4odmHYKyG2uKCvYyrSfn3-K5?usp=sharing?

**Comment by pieper** [comment]
See: https://github.com/ImagingDataCommons/IDC-Viewer-Support/pull/3

**Comment by pieper** [comment]
Once this is merged we can see if anything else needs to be changed (e.g. size or position).  I didn't test on sandbox.

**Comment by pieper** [comment]
This looks okay to me in the release.
